unity:
  scene_id: 0 # 0 warehouse, 1 garage, 3 natureforest
  render: no

simulation:
  seed: 1
  sim_dt: 0.02
  max_t: 20.0
  num_envs: 100
  num_threads: 10
  rotor_ctrl: 1 # 0 single rotor, 1 body rate

quadrotor_dynamics:
  mass: 0.752
  tbm_fr: [0.075, -0.10, 0.0] # [m]
  tbm_bl: [-0.075, 0.10, 0.0] # [m]
  tbm_br: [-0.075, -0.10, 0.0] # [m]
  tbm_fl: [0.075, 0.10, 0.0] # [m
  omega_max: [6.0, 6.0, 2.0]
  inertia: [0.0025, 0.0021, 0.0043]
  kappa: 0.022
  motor_omega_min: 150.0
  motor_omega_max: 2333.0
  motor_tau: 0.033
  thrust_map: [1.562522e-6, 0.0, 0.0] # max thrust = 8.50 N
  body_drag_1: [0.26, 0.28, 0.42]
  body_drag_3: [0.00, 0.00, 0.00]
  body_drag_h: 0.01

rewards:
  progress_coeff: 0.5 # reward coefficient for position 
  tracking_coeff: -0.01 # reward coefficient for orientation
  collision: -7
  pass_gate: 2
  gate_pass_threshold: 0.5
  time_penalty: -0.004
  terminal: 50
  names:
    [
      progress_reward,
      tracking_penalty,
      pass_gate_reward,
      time_penalty,
      total,
    ]
    
initState:
  pos: [1.21, 10.42, 0.15]
  rot: [0.0, 0.0, 0.0]
endState:
  pos: [1.21, 10.42, 0.15]
  rot: [0.0, 0.0, 0.0]

gates:
  gate_order: [gate1, gate2, gate3, gate4, gate5, gate6, gate7, gate8, gate9, gate10]
  gate1:
    position: [3.65, 13.13, 1.45]
    rotation: [0.0, -90, 43.62]
  gate2:
    position: [10.16, 11.35, 1.45]
    rotation: [0.0, -90.0, -15.07]
  gate3:
    position: [15.59, 14.95, 1.45]
    rotation: [0.0, -90, 54.82]
  gate4:
    position: [15.59, 14.95, 4.15]
    rotation: [0.0, -90, 54.82]
  gate5:
    position: [18.79, 17.88, 4.15]
    rotation: [0.0, -90, 90.0]
  gate6:
    position: [18.79, 17.88, 1.45]
    rotation: [0.0, -90.0, -90.0]
  gate7:
    position: [20.51, 9.9, 1.45]
    rotation: [0.0, -90, -90]
  gate8:
    position: [15.75, 1.83, 1.45]
    rotation: [0.0, -90, 180]
  gate9:
    position: [10.25, 5.35, 1.45]
    rotation: [0.0, -90, 180]
  gate10:
    position: [4.75, 1.83, 1.45]
    rotation: [0.0, -90, 180]

rgb_camera:
  on: yes
  t_BC: [0.0, 0.0, 0.3] # translational vector of the camera with repect to the body frame
  r_BC: [0.0, 0.0, -90] # rotational angle (roll, pitch, yaw) of the camera in degree.
  channels: 3
  width: 720
  height: 480
  fov: 70.0
  enable_depth: yes 
  enable_segmentation: no
  enable_opticalflow: no
